# Form implementation generated from reading ui file 'project1.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fitnessClassScheduler(object):
    def setupUi(self, fitnessClassScheduler):
        fitnessClassScheduler.setObjectName("fitnessClassScheduler")
        fitnessClassScheduler.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        fitnessClassScheduler.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=fitnessClassScheduler)
        self.centralwidget.setObjectName("centralwidget")
        self.lblGymName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGymName.setGeometry(QtCore.QRect(130, 30, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        self.lblGymName.setFont(font)
        self.lblGymName.setObjectName("lblGymName")
        self.lblYoga = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblYoga.setGeometry(QtCore.QRect(80, 80, 141, 16))
        self.lblYoga.setObjectName("lblYoga")
        self.lblRockClimbing = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblRockClimbing.setGeometry(QtCore.QRect(30, 120, 201, 16))
        self.lblRockClimbing.setObjectName("lblRockClimbing")
        self.lblPilates = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPilates.setGeometry(QtCore.QRect(70, 160, 151, 20))
        self.lblPilates.setObjectName("lblPilates")
        self.txtYoga = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtYoga.setGeometry(QtCore.QRect(230, 80, 113, 20))
        self.txtYoga.setObjectName("txtYoga")
        self.txtRockClimbing = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtRockClimbing.setGeometry(QtCore.QRect(230, 120, 113, 20))
        self.txtRockClimbing.setObjectName("txtRockClimbing")
        self.txtPilates = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtPilates.setGeometry(QtCore.QRect(230, 160, 113, 20))
        self.txtPilates.setObjectName("txtPilates")
        self.lblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(160, 200, 61, 20))
        self.lblTime.setObjectName("lblTime")
        self.txtTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTime.setGeometry(QtCore.QRect(230, 200, 113, 20))
        self.txtTime.setObjectName("txtTime")
        self.lblYogaPrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblYogaPrice.setGeometry(QtCore.QRect(360, 80, 101, 16))
        self.lblYogaPrice.setObjectName("lblYogaPrice")
        self.lblRockClimbingPrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblRockClimbingPrice.setGeometry(QtCore.QRect(360, 120, 101, 16))
        self.lblRockClimbingPrice.setObjectName("lblRockClimbingPrice")
        self.lblPilatesPrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPilatesPrice.setGeometry(QtCore.QRect(360, 160, 91, 16))
        self.lblPilatesPrice.setObjectName("lblPilatesPrice")
        self.btnConfirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnConfirm.setGeometry(QtCore.QRect(230, 240, 111, 23))
        self.btnConfirm.setObjectName("btnConfirm")
        self.lblTotal = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTotal.setGeometry(QtCore.QRect(160, 270, 61, 20))
        self.lblTotal.setObjectName("lblTotal")
        self.txtTotal = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTotal.setGeometry(QtCore.QRect(230, 270, 113, 20))
        self.txtTotal.setReadOnly(True)
        self.txtTotal.setObjectName("txtTotal")
        fitnessClassScheduler.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fitnessClassScheduler)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        fitnessClassScheduler.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fitnessClassScheduler)
        self.statusbar.setObjectName("statusbar")
        fitnessClassScheduler.setStatusBar(self.statusbar)

        self.retranslateUi(fitnessClassScheduler)
        QtCore.QMetaObject.connectSlotsByName(fitnessClassScheduler)
        
        #When the btnConfirm button is clicked,execute the function "calculate"
        self.btnConfirm.clicked.connect(self.calculate)

    def retranslateUi(self, fitnessClassScheduler):
        _translate = QtCore.QCoreApplication.translate
        fitnessClassScheduler.setWindowTitle(_translate("fitnessClassScheduler", "Fitness Class Scheduler"))
        self.lblGymName.setText(_translate("fitnessClassScheduler", "Carmichael Fitness Classes"))
        self.lblYoga.setText(_translate("fitnessClassScheduler", " Number of Yoga classes"))
        self.lblRockClimbing.setText(_translate("fitnessClassScheduler", "Number of Rock-climbing classes"))
        self.lblPilates.setText(_translate("fitnessClassScheduler", "Number of Pilates classes"))
        self.lblTime.setText(_translate("fitnessClassScheduler", "Time Slot"))
        self.lblYogaPrice.setText(_translate("fitnessClassScheduler", "$10.00 per class"))
        self.lblRockClimbingPrice.setText(_translate("fitnessClassScheduler", "$12.00 per class"))
        self.lblPilatesPrice.setText(_translate("fitnessClassScheduler", "$15.00 per class"))
        self.btnConfirm.setText(_translate("fitnessClassScheduler", "Confirm Booking"))
        self.lblTotal.setText(_translate("fitnessClassScheduler", "Total Cost"))
        
    def calculate(self):
        #Extract Number of Yoga classes entered by the user and convert it into integer and store it in yoga_classes variable
        yoga_classes = int(self.txtYoga.text())
        #Extract Number of Rock-climbing classes entered by the user and convert it into integer and store it in rockclimbing_class
        rockclimbing_classes = int(self.txtRockClimbing.text())
        #Extract Number of Pilates classes entered by the user and convert it into integer and store it in pilates_classes
        pilates_classes = int(self.txtPilates.text())
        #Extract time slot entered ("Morning" or "Evening") by the user and store it in time_slot
        time_slot = self.txtTime.text()
        
        #Check to find if the txtTime says "Morning" or "Evening"
        #If user enters "Morning", add $0 as the extra fee variable
        if (time_slot == "Morning"):
            extra_fee = 0.0
        #If not entered morning, check if the  user enters "Evening", add $5.0 as the extra fee variable
        elif (time_slot == "Evening"):
            extra_fee = 5.0
        #Multiply each of the yoga_classes, rockclimbing_classes and pilates_classes with the price per class amount
        #Add extra_fee variable and then store it as total_cost
        total_cost = (yoga_classes*10)+(rockclimbing_classes*12)+(pilates_classes*15)+extra_fee
        #Convert total_cost variable into string and display it on txtTotal lineedit box
        self.txtTotal.setText(str(total_cost))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fitnessClassScheduler = QtWidgets.QMainWindow()
    ui = Ui_fitnessClassScheduler()
    ui.setupUi(fitnessClassScheduler)
    fitnessClassScheduler.show()
    sys.exit(app.exec())
