# Form implementation generated from reading ui file 'secondwindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_secondWindow(object):
    def setupUi(self, secondWindow):
        secondWindow.setObjectName("secondWindow")
        secondWindow.resize(551, 223)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        secondWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=secondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblText = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblText.setGeometry(QtCore.QRect(50, 60, 101, 16))
        self.lblText.setObjectName("lblText")
        self.txtTranferredText = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTranferredText.setGeometry(QtCore.QRect(160, 60, 113, 20))
        self.txtTranferredText.setObjectName("txtTranferredText")
        secondWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=secondWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 21))
        self.menubar.setObjectName("menubar")
        secondWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=secondWindow)
        self.statusbar.setObjectName("statusbar")
        secondWindow.setStatusBar(self.statusbar)

        self.retranslateUi(secondWindow)
        QtCore.QMetaObject.connectSlotsByName(secondWindow)

    def retranslateUi(self, secondWindow):
        _translate = QtCore.QCoreApplication.translate
        secondWindow.setWindowTitle(_translate("secondWindow", "Second Window"))
        self.lblText.setText(_translate("secondWindow", "Transferred Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    secondWindow = QtWidgets.QMainWindow()
    ui = Ui_secondWindow()
    ui.setupUi(secondWindow)
    secondWindow.show()
    sys.exit(app.exec())
