# Form implementation generated from reading ui file 'studentscores.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_studentScores(object):
    def setupUi(self, studentScores):
        studentScores.setObjectName("studentScores")
        studentScores.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=studentScores)
        self.centralwidget.setObjectName("centralwidget")
        self.lstScores = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstScores.setGeometry(QtCore.QRect(260, 60, 256, 192))
        self.lstScores.setObjectName("lstScores")
        self.lblScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScores.setGeometry(QtCore.QRect(350, 30, 81, 16))
        self.lblScores.setObjectName("lblScores")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(340, 270, 101, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblAverage = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAverage.setGeometry(QtCore.QRect(280, 320, 81, 16))
        self.lblAverage.setObjectName("lblAverage")
        self.txt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt.setGeometry(QtCore.QRect(390, 320, 113, 20))
        self.txt.setReadOnly(True)
        self.txt.setObjectName("txt")
        studentScores.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentScores)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        studentScores.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentScores)
        self.statusbar.setObjectName("statusbar")
        studentScores.setStatusBar(self.statusbar)

        self.retranslateUi(studentScores)
        QtCore.QMetaObject.connectSlotsByName(studentScores)
        #Create an empty dicitionary to store student data
        self.student_scores_dictionary={}
        self.load_data("studentdata.txt")
        
        self.btnCalculate.clicked.connect(self.calculate_average)
        
    def calculate_average(self):
        if(len(self.student_scores_dictionary)>0):
            total=0
            for value in self.student_scores_dictionary.values():
                total = total+value
            average = total/len(self.student_scores_dictionary)
            self.txt.setText(str(average))
        else:
            msg=QtWidgets.QMessageBox()
            msg.setWindowTitle("Student Scores")
            msg.setText("No student data in the dictionary")
            msg.exec()
        
    def load_data(self, file_name):
        #Open the external file in read mode
        with open(file_name,"r") as filename:
            #iterate over each line of the file
            for line in filename:
                #split the name and score by the comma delimiter
                data=line.split(",")
                #create a key and value pair and store the data in the dictionary.
                self.student_scores_dictionary[data[0]]=int(data[1].strip())
                self.lstScores.addItem(f"{data[0]}  {data[1].strip()}")

    def retranslateUi(self, studentScores):
        _translate = QtCore.QCoreApplication.translate
        studentScores.setWindowTitle(_translate("studentScores", "Student Scores"))
        self.lblScores.setText(_translate("studentScores", "Student Scores"))
        self.btnCalculate.setText(_translate("studentScores", "Average Score"))
        self.lblAverage.setText(_translate("studentScores", "Average Score"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentScores = QtWidgets.QMainWindow()
    ui = Ui_studentScores()
    ui.setupUi(studentScores)
    studentScores.show()
    sys.exit(app.exec())
