# Form implementation generated from reading ui file 'fruitpurchase.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fruitpurchase(object):
    def setupUi(self, fruitpurchase):
        fruitpurchase.setObjectName("fruitpurchase")
        fruitpurchase.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        fruitpurchase.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=fruitpurchase)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFruit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFruit.setGeometry(QtCore.QRect(230, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblFruit.setFont(font)
        self.lblFruit.setObjectName("lblFruit")
        self.cmbFruit = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbFruit.setGeometry(QtCore.QRect(330, 120, 111, 22))
        self.cmbFruit.setObjectName("cmbFruit")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.lblQuantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblQuantity.setGeometry(QtCore.QRect(230, 150, 81, 16))
        self.lblQuantity.setObjectName("lblQuantity")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtQuantity.setGeometry(QtCore.QRect(330, 150, 113, 20))
        self.txtQuantity.setObjectName("txtQuantity")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(330, 180, 111, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCost.setGeometry(QtCore.QRect(230, 220, 61, 16))
        self.lblCost.setObjectName("lblCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCost.setGeometry(QtCore.QRect(330, 220, 113, 20))
        self.txtCost.setReadOnly(True)
        self.txtCost.setObjectName("txtCost")
        self.lblPrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPrice.setGeometry(QtCore.QRect(520, 120, 121, 16))
        self.lblPrice.setText("")
        self.lblPrice.setObjectName("lblPrice")
        fruitpurchase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fruitpurchase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        fruitpurchase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fruitpurchase)
        self.statusbar.setObjectName("statusbar")
        fruitpurchase.setStatusBar(self.statusbar)

        self.retranslateUi(fruitpurchase)
        QtCore.QMetaObject.connectSlotsByName(fruitpurchase)
        
        self.fruit_price = {"Apple": 3.50, "Orange":3.99, "Pear":4.10, "Peach": 5.99, "Banana": 1.29}
        
        self.cmbFruit.currentIndexChanged.connect(self.display_price)
        
        self.btnCalculate.clicked.connect(self.calculate)
        
        #To create a global variable
        #self.fruit_selection ="" 
        
    def calculate(self):
        #To do: add input validation
        number_of_pounds = float(self.txtQuantity.text())
        fruit_selection = self.cmbFruit.currentText()
        if(fruit_selection in self.fruit_price.keys()):
            price = self.fruit_price.get(fruit_selection)
            total_cost = number_of_pounds*price
            self.txtCost.setText(str(f"${total_cost:.2f}"))
        else:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Fruit Purchase")
            msg.setText("Please select a fruit from the dropdown")
            msg.exec()
    
    def display_price(self):
        #Store the current selected fruit in the variable/object fruit_selection
        fruit_selection=self.cmbFruit.currentText()
        if(fruit_selection in self.fruit_price.keys()):
            #Get the price per pound from the fruit_price dictionary
            price=self.fruit_price.get(fruit_selection)
            #Display the price to the user using the label
            self.lblPrice.setText(f"${price:.2f} per pound")
        else:
            self.lblPrice.setText("")

    def retranslateUi(self, fruitpurchase):
        _translate = QtCore.QCoreApplication.translate
        fruitpurchase.setWindowTitle(_translate("fruitpurchase", "Fruit Purchase"))
        self.lblFruit.setText(_translate("fruitpurchase", "Select a fruit"))
        self.cmbFruit.setItemText(0, _translate("fruitpurchase", "Fruit selection"))
        self.cmbFruit.setItemText(1, _translate("fruitpurchase", "Apple"))
        self.cmbFruit.setItemText(2, _translate("fruitpurchase", "Orange"))
        self.cmbFruit.setItemText(3, _translate("fruitpurchase", "Pear"))
        self.cmbFruit.setItemText(4, _translate("fruitpurchase", "Peach"))
        self.cmbFruit.setItemText(5, _translate("fruitpurchase", "Banana"))
        self.lblQuantity.setText(_translate("fruitpurchase", "Enter quantity"))
        self.btnCalculate.setText(_translate("fruitpurchase", "Calculate Cost"))
        self.lblCost.setText(_translate("fruitpurchase", "Total cost"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fruitpurchase = QtWidgets.QMainWindow()
    ui = Ui_fruitpurchase()
    ui.setupUi(fruitpurchase)
    fruitpurchase.show()
    sys.exit(app.exec())
