# Form implementation generated from reading ui file 'gradecalculator.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_gradeCalculator(object):
    def setupUi(self, gradeCalculator):
        gradeCalculator.setObjectName("gradeCalculator")
        gradeCalculator.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        gradeCalculator.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=gradeCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(130, 120, 111, 16))
        self.lblScore.setObjectName("lblScore")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(250, 160, 131, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(260, 120, 113, 20))
        self.txtScore.setObjectName("txtScore")
        self.lblGrade = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGrade.setGeometry(QtCore.QRect(130, 200, 111, 16))
        self.lblGrade.setObjectName("lblGrade")
        self.txtGrade = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtGrade.setGeometry(QtCore.QRect(260, 200, 113, 20))
        self.txtGrade.setReadOnly(True)
        self.txtGrade.setObjectName("txtGrade")
        gradeCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=gradeCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        gradeCalculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=gradeCalculator)
        self.statusbar.setObjectName("statusbar")
        gradeCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(gradeCalculator)
        QtCore.QMetaObject.connectSlotsByName(gradeCalculator)
        
        self.btnCalculate.clicked.connect(self.calculate)

    def retranslateUi(self, gradeCalculator):
        _translate = QtCore.QCoreApplication.translate
        gradeCalculator.setWindowTitle(_translate("gradeCalculator", "Grade Calculator"))
        self.lblScore.setText(_translate("gradeCalculator", "Enter Student Score"))
        self.btnCalculate.setText(_translate("gradeCalculator", "Calculate Grade"))
        self.lblGrade.setText(_translate("gradeCalculator", "Student Grade"))
    
    #To do: Add input validations to the code    
    def calculate(self):
        #Read the input score entered by the user and store in variable input_score
        input_score= self.txtScore.text()
        #Create a new message box instance
        msg=QtWidgets.QMessageBox()
        #Set the message box window title
        msg.setWindowTitle("Grade Calculator")
        #Input validation to ensure user enters only numeric values
        if(input_score.isdigit()):
            #Convert the string to an integer value
            input_score=int(input_score)
            #Input validation to ensure value entered is between 0 and 100
            if(input_score>=0 and input_score<=100):
                #Grade calculation
                if(input_score >=90):
                    grade = "A"
                elif(input_score >=80):
                    grade="B"
                elif(input_score >=70):
                    grade="C"
                elif(input_score >=60):
                    grade="D"
                else:
                    grade="F"
                self.txtGrade.setText(grade)
            else:
                
                #Set the message box text
                msg.setText("Please enter a score between 0 and 100")
                #Execute the message box
                msg.exec()
        else:
            
            msg.setText("Please enter a numeric value")
            msg.exec()
            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gradeCalculator = QtWidgets.QMainWindow()
    ui = Ui_gradeCalculator()
    ui.setupUi(gradeCalculator)
    gradeCalculator.show()
    sys.exit(app.exec())
