# Form implementation generated from reading ui file 'financialplanner.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_financialPlanner(object):
    def setupUi(self, financialPlanner):
        financialPlanner.setObjectName("financialPlanner")
        financialPlanner.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        financialPlanner.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=financialPlanner)
        self.centralwidget.setObjectName("centralwidget")
        self.lblInitialInvestment = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblInitialInvestment.setGeometry(QtCore.QRect(140, 110, 91, 16))
        self.lblInitialInvestment.setObjectName("lblInitialInvestment")
        self.txtTarget = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTarget.setGeometry(QtCore.QRect(260, 140, 113, 20))
        self.txtTarget.setObjectName("txtTarget")
        self.lblTarget = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTarget.setGeometry(QtCore.QRect(140, 140, 91, 16))
        self.lblTarget.setObjectName("lblTarget")
        self.txtInitialInvestment = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtInitialInvestment.setGeometry(QtCore.QRect(260, 110, 113, 20))
        self.txtInitialInvestment.setObjectName("txtInitialInvestment")
        self.lblPlan = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPlan.setGeometry(QtCore.QRect(120, 180, 131, 16))
        self.lblPlan.setObjectName("lblPlan")
        self.cmbPlan = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbPlan.setGeometry(QtCore.QRect(270, 180, 91, 22))
        self.cmbPlan.setObjectName("cmbPlan")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(280, 210, 75, 23))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(140, 250, 71, 16))
        self.lblTime.setObjectName("lblTime")
        self.txtTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTime.setGeometry(QtCore.QRect(260, 250, 113, 20))
        self.txtTime.setReadOnly(True)
        self.txtTime.setObjectName("txtTime")
        financialPlanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=financialPlanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        financialPlanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=financialPlanner)
        self.statusbar.setObjectName("statusbar")
        financialPlanner.setStatusBar(self.statusbar)

        self.retranslateUi(financialPlanner)
        QtCore.QMetaObject.connectSlotsByName(financialPlanner)
        
        self.btnCalculate.clicked.connect(self.calculate)

    def retranslateUi(self, financialPlanner):
        _translate = QtCore.QCoreApplication.translate
        financialPlanner.setWindowTitle(_translate("financialPlanner", "Financial Planner"))
        self.lblInitialInvestment.setText(_translate("financialPlanner", "Initial Investment"))
        self.lblTarget.setText(_translate("financialPlanner", "Target Amount"))
        self.lblPlan.setText(_translate("financialPlanner", "Select Retirement Plan"))
        self.cmbPlan.setItemText(0, _translate("financialPlanner", "Plan 2040"))
        self.cmbPlan.setItemText(1, _translate("financialPlanner", "Plan 2050"))
        self.cmbPlan.setItemText(2, _translate("financialPlanner", "Plan 2060"))
        self.btnCalculate.setText(_translate("financialPlanner", "Calculate"))
        self.lblTime.setText(_translate("financialPlanner", "Time Taken"))
        
    def calculate(self):
        initial_investment=int(self.txtInitialInvestment.text())
        target_amount=int(self.txtTarget.text())
        #Store the current selected retirement plan in variable retirement_plan
        retirement_plan=self.cmbPlan.currentText()
        
        current_portfolio_value=0
        time_taken=0
        
        if(retirement_plan == "Plan 2040"):
            rate=7.0
        elif(retirement_plan== "Plan 2050"):
            rate=6.0
        else:
            rate=5.0
            
        while(current_portfolio_value < target_amount):
            current_portfolio_value=(current_portfolio_value + initial_investment)*(1+rate/100)
            time_taken = time_taken + 1
            
        self.txtTime.setText(str(time_taken))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    financialPlanner = QtWidgets.QMainWindow()
    ui = Ui_financialPlanner()
    ui.setupUi(financialPlanner)
    financialPlanner.show()
    sys.exit(app.exec())
