# Form implementation generated from reading ui file 'dashboardwindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
#To import second window (purchase window) ui
from purchasewindow import Ui_purchaseWindow
#To import third window (search window) ui
from searchwindow import Ui_searchWindow
#To import fourth window (diaply window) ui
from displaywindow import Ui_displayWindow

class Ui_dashboardWindow(object):
    def setupUi(self, dashboardWindow):
        dashboardWindow.setObjectName("dashboardWindow")
        dashboardWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        dashboardWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=dashboardWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(320, 130, 113, 20))
        self.txtName.setObjectName("txtName")
        self.lblName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(220, 130, 101, 16))
        self.lblName.setObjectName("lblName")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPurchase.setGeometry(QtCore.QRect(240, 170, 75, 23))
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(330, 170, 75, 23))
        self.btnSearch.setObjectName("btnSearch")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(240, 200, 75, 23))
        self.btnDisplay.setObjectName("btnDisplay")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(330, 200, 75, 23))
        self.btnExit.setObjectName("btnExit")
        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(250, 70, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        dashboardWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=dashboardWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        dashboardWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=dashboardWindow)
        self.statusbar.setObjectName("statusbar")
        dashboardWindow.setStatusBar(self.statusbar)

        self.retranslateUi(dashboardWindow)
        QtCore.QMetaObject.connectSlotsByName(dashboardWindow)
        
        #When btnPurchase is clicked, to execute the purchase function
        self.btnPurchase.clicked.connect(self.purchase)
        #When btnSearch is clicked, to execute the search function
        self.btnSearch.clicked.connect(self.search)
        #When btnDisplay is clicked, to execute the display function
        self.btnDisplay.clicked.connect(self.display)
        #When btnExit is clicked, to execute the appexit function
        self.btnExit.clicked.connect(self.appexit)
    
    #Define the purchase function
    def purchase(self):
        #the lines under the code will be excuted normally under the exception handling 
        try:
            #Create an empty Main Window
            self.window=QtWidgets.QMainWindow()
            #Create a new object from the second application
            self.secondui= Ui_purchaseWindow()
            #Call the setupUi function of the second application
            self.secondui.setupUi(self.window)
            #display the window
            self.window.show()
            # Read the data from the name text box in the first application (and make sure its a string)
            customer_name= str(self.txtName.text())
            #Set the text property of the text box/lineedit widget of the second application
            self.secondui.txtName.setText(customer_name)
         #If not, print a exception message
        except Exception as e:
            print(e)
    
    #Define the search function
    def search(self):
        #the lines under the code will be excuted normally under the exception handling 
        try:
            #Create an empty Main Window
            self.window=QtWidgets.QMainWindow()
            #Create a new object from the third application
            self.thirdui= Ui_searchWindow()
            #Call the setupUi function of the third application
            self.thirdui.setupUi(self.window)
            #display the window
            self.window.show()
         #If not, print a exception message
        except Exception as e:
            print(e)

    #Define the display function
    def display(self):
        #the lines under the code will be excuted normally under the exception handling 
        try:
            #Create an empty Main Window
            self.window=QtWidgets.QMainWindow()
            #Create a new object from the fourth application
            self.fourthui= Ui_displayWindow()
            #Call the setupUi function of the fourth application
            self.fourthui.setupUi(self.window)
            #display the window
            self.window.show()
         #If not, print a exception message
        except Exception as e:
            print(e)
        
    #Define the appexit function
    def appexit(self):
        #the lines under the code will be excuted normally under the exception handling 
        try:
            #Close the python window
            QtWidgets.QApplication.quit()
         #If not, print a exception message
        except Exception as e:
            print(e)

    def retranslateUi(self, dashboardWindow):
        _translate = QtCore.QCoreApplication.translate
        dashboardWindow.setWindowTitle(_translate("dashboardWindow", "Dashboard Window"))
        self.lblName.setText(_translate("dashboardWindow", "Customer Name"))
        self.btnPurchase.setText(_translate("dashboardWindow", "Purchase"))
        self.btnSearch.setText(_translate("dashboardWindow", "Search"))
        self.btnDisplay.setText(_translate("dashboardWindow", "Display"))
        self.btnExit.setText(_translate("dashboardWindow", "Exit"))
        self.lblTitle.setText(_translate("dashboardWindow", "Book Purchase App"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dashboardWindow = QtWidgets.QMainWindow()
    ui = Ui_dashboardWindow()
    ui.setupUi(dashboardWindow)
    dashboardWindow.show()
    sys.exit(app.exec())
