# Form implementation generated from reading ui file 'displaywindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
#From PyQt6, import the QTableWidgetItem
from PyQt6.QtWidgets import QTableWidgetItem
#import the pymsql package from my Python library
import pymysql as mdb

class Ui_displayWindow(object):
    def setupUi(self, displayWindow):
        displayWindow.setObjectName("displayWindow")
        displayWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        displayWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=displayWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTransaction = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTransaction.setGeometry(QtCore.QRect(340, 130, 91, 20))
        self.lblTransaction.setObjectName("lblTransaction")
        self.tblTransaction = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblTransaction.setGeometry(QtCore.QRect(20, 150, 751, 251))
        self.tblTransaction.setObjectName("tblTransaction")
        self.tblTransaction.setColumnCount(0)
        self.tblTransaction.setRowCount(0)
        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(310, 90, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        displayWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=displayWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        displayWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=displayWindow)
        self.statusbar.setObjectName("statusbar")
        displayWindow.setStatusBar(self.statusbar)

        self.retranslateUi(displayWindow)
        QtCore.QMetaObject.connectSlotsByName(displayWindow)
        
        #Estlabish dataase conenction
        self.connecttodb()
        #To load the data from the text file
        self.load_data()
        
    #define the connecttodb function
    def connecttodb(self):
        #the lines under the code will be excuted normally under the exception handling 
        try:
            #connect to the speficied host, user with the password, database and port
            connection = mdb.connect(host="localhost", user = "dbuser", password="dbuser", database = "finalprojectdb", port =3306)             
            #if able to connect, return the connection
            return connection
        # If connection fails, print the exception error
        except Exception as e:
            print(e)
    
    #Define the load_data function
    def load_data(self):
        #the lines under the code will be excuted normally under the exception handling 
        try:
            #connect to the database
            connectionobj= self.connecttodb()
            #Create a cursor object
            cursorobj=connectionobj.cursor()
         
            #Execute SQL query "select * from book_sales")
            cursorobj.execute("select * from book_sales")
            #results variable is saved all the rows fetched from the query
            results = cursorobj.fetchall()
            #Find number of rows in the result set
            row_length = len(results)
            #Find number of columns in the result set
            col_length = len(cursorobj.description)
            #Label the column headers
            col_header = ["Transaction Id", "Name", "Book Title", "Quantity", "Total"]
            #Set the number of rows
            self.tblTransaction.setRowCount(row_length)
            #Set the number of columns
            self.tblTransaction.setColumnCount(col_length)
            #Set the column headers
            self.tblTransaction.setHorizontalHeaderLabels(col_header)
            
            #Display the table, all the rows and columnn
            for rownumber, rowdata in enumerate(results):
                for colnumber, coldata in enumerate(rowdata):
                    #Insert each of the data into table
                    self.tblTransaction.setItem(rownumber, colnumber, QTableWidgetItem(str(coldata)))
            
        # If connection fails, print the exception error
        except Exception as e:
            print(e)
        #Close the connection
        finally:
            connectionobj.close()

    def retranslateUi(self, displayWindow):
        _translate = QtCore.QCoreApplication.translate
        displayWindow.setWindowTitle(_translate("displayWindow", "Display Window"))
        self.lblTransaction.setText(_translate("displayWindow", "All Transactions"))
        self.lblTitle.setText(_translate("displayWindow", "Book Purchase App"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    displayWindow = QtWidgets.QMainWindow()
    ui = Ui_displayWindow()
    ui.setupUi(displayWindow)
    displayWindow.show()
    sys.exit(app.exec())
