# Form implementation generated from reading ui file 'streetfighter.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Player:
    def __init__(self,player_name, player_power, player_speed, player_agility):
        self.name=player_name
        self.power = player_power
        self.speed=player_speed
        self.agility=player_agility
        
    def modify_stats(self, player_power, player_speed, player_agility):
        self.power=player_power
        self.speed=player_speed
        self.agility=player_agility
        

class Ui_streetFighter(object):
    def setupUi(self, streetFighter):
        streetFighter.setObjectName("streetFighter")
        streetFighter.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        streetFighter.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=streetFighter)
        self.centralwidget.setObjectName("centralwidget")
        self.tbStreetFighter = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbStreetFighter.setGeometry(QtCore.QRect(60, 40, 731, 411))
        self.tbStreetFighter.setObjectName("tbStreetFighter")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lblName_2 = QtWidgets.QLabel(parent=self.tab)
        self.lblName_2.setGeometry(QtCore.QRect(30, 20, 101, 16))
        self.lblName_2.setObjectName("lblName_2")
        self.txtName = QtWidgets.QLineEdit(parent=self.tab)
        self.txtName.setGeometry(QtCore.QRect(140, 20, 113, 20))
        self.txtName.setObjectName("txtName")
        self.lblPower = QtWidgets.QLabel(parent=self.tab)
        self.lblPower.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.lblPower.setObjectName("lblPower")
        self.txtPower = QtWidgets.QLineEdit(parent=self.tab)
        self.txtPower.setGeometry(QtCore.QRect(140, 50, 113, 20))
        self.txtPower.setObjectName("txtPower")
        self.lblSpeed = QtWidgets.QLabel(parent=self.tab)
        self.lblSpeed.setGeometry(QtCore.QRect(30, 80, 101, 16))
        self.lblSpeed.setObjectName("lblSpeed")
        self.txtSpeed = QtWidgets.QLineEdit(parent=self.tab)
        self.txtSpeed.setGeometry(QtCore.QRect(140, 80, 113, 20))
        self.txtSpeed.setObjectName("txtSpeed")
        self.lblAgility = QtWidgets.QLabel(parent=self.tab)
        self.lblAgility.setGeometry(QtCore.QRect(30, 110, 101, 16))
        self.lblAgility.setObjectName("lblAgility")
        self.txtAgility = QtWidgets.QLineEdit(parent=self.tab)
        self.txtAgility.setGeometry(QtCore.QRect(140, 110, 113, 20))
        self.txtAgility.setObjectName("txtAgility")
        self.btnCreatePlayer = QtWidgets.QPushButton(parent=self.tab)
        self.btnCreatePlayer.setGeometry(QtCore.QRect(144, 150, 91, 23))
        self.btnCreatePlayer.setObjectName("btnCreatePlayer")
        self.tbStreetFighter.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lstPlayers = QtWidgets.QListWidget(parent=self.tab_2)
        self.lstPlayers.setGeometry(QtCore.QRect(10, 50, 381, 191))
        self.lstPlayers.setObjectName("lstPlayers")
        self.lblCreatedPlayers = QtWidgets.QLabel(parent=self.tab_2)
        self.lblCreatedPlayers.setGeometry(QtCore.QRect(10, 20, 131, 16))
        self.lblCreatedPlayers.setObjectName("lblCreatedPlayers")
        self.lblModifiedPower = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModifiedPower.setGeometry(QtCore.QRect(20, 260, 81, 16))
        self.lblModifiedPower.setObjectName("lblModifiedPower")
        self.txtModifiedPower = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModifiedPower.setGeometry(QtCore.QRect(20, 280, 113, 20))
        self.txtModifiedPower.setObjectName("txtModifiedPower")
        self.ModifiedSpeed = QtWidgets.QLabel(parent=self.tab_2)
        self.ModifiedSpeed.setGeometry(QtCore.QRect(160, 260, 81, 16))
        self.ModifiedSpeed.setObjectName("ModifiedSpeed")
        self.txtModifiedSpeed = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModifiedSpeed.setGeometry(QtCore.QRect(150, 280, 113, 20))
        self.txtModifiedSpeed.setObjectName("txtModifiedSpeed")
        self.ModifiedAgility = QtWidgets.QLabel(parent=self.tab_2)
        self.ModifiedAgility.setGeometry(QtCore.QRect(280, 260, 81, 16))
        self.ModifiedAgility.setObjectName("ModifiedAgility")
        self.txtModifiedAgility = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModifiedAgility.setGeometry(QtCore.QRect(280, 280, 113, 20))
        self.txtModifiedAgility.setObjectName("txtModifiedAgility")
        self.btnModifyPlayer = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnModifyPlayer.setGeometry(QtCore.QRect(140, 320, 101, 23))
        self.btnModifyPlayer.setObjectName("btnModifyPlayer")
        self.tbStreetFighter.addTab(self.tab_2, "")
        streetFighter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=streetFighter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        streetFighter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=streetFighter)
        self.statusbar.setObjectName("statusbar")
        streetFighter.setStatusBar(self.statusbar)

        self.retranslateUi(streetFighter)
        self.tbStreetFighter.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(streetFighter)
        
        #Creating an empty dictionary to store players
        self.created_players={}
        
        self.btnCreatePlayer.clicked.connect(self.create_player)
        
        self.lstPlayers.itemClicked.connect(self.display_stats)
        
        self.btnModifyPlayer.clicked.connect(self.modify_player)
        #To do:
            #1) Input validation
            #2) Exception handling
            #3) Message boxes
            #4) Add comments
    def modify_player(self):
        player_name=self.lstPlayers.currentItem().text()
        player_object=self.created_players.get(player_name)
        modified_power = self.txtModifiedPower.text()
        modified_speed = self.txtModifiedSpeed.text()
        modified_agility= self.txtModifiedAgility.text()
        
        player_object.modify_stats(modified_power,modified_speed,modified_agility)
        
    def display_stats(self):
        player_name=self.lstPlayers.currentItem().text()
        player_object=self.created_players.get(player_name)
        self.txtModifiedPower.setText(player_object.power)
        self.txtModifiedSpeed.setText(player_object.speed)
        self.txtModifiedAgility.setText(player_object.agility)
        
        
    
    def create_player(self):
        player_name=self.txtName.text()
        player_power=self.txtPower.text()
        player_speed=self.txtSpeed.text()
        player_agility=self.txtAgility.text()
        #Player object creation
        player_object=Player(player_name, player_power, player_speed, player_agility)
        #Storing the player object in the dictionary
        self.created_players[player_name]=player_object
        
        self.lstPlayers.addItem(player_name)

    def retranslateUi(self, streetFighter):
        _translate = QtCore.QCoreApplication.translate
        streetFighter.setWindowTitle(_translate("streetFighter", "Street Fighter"))
        self.lblName_2.setText(_translate("streetFighter", "Enter player name"))
        self.lblPower.setText(_translate("streetFighter", "Enter player power"))
        self.lblSpeed.setText(_translate("streetFighter", "Enter player speed"))
        self.lblAgility.setText(_translate("streetFighter", "Enter player agility"))
        self.btnCreatePlayer.setText(_translate("streetFighter", "Create Player"))
        self.tbStreetFighter.setTabText(self.tbStreetFighter.indexOf(self.tab), _translate("streetFighter", "Create Player"))
        self.lblCreatedPlayers.setText(_translate("streetFighter", "List of Created Players"))
        self.lblModifiedPower.setText(_translate("streetFighter", "Player Power"))
        self.ModifiedSpeed.setText(_translate("streetFighter", "Player Speed"))
        self.ModifiedAgility.setText(_translate("streetFighter", "Player Agility"))
        self.btnModifyPlayer.setText(_translate("streetFighter", "Modify Player"))
        self.tbStreetFighter.setTabText(self.tbStreetFighter.indexOf(self.tab_2), _translate("streetFighter", "Modify Player"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    streetFighter = QtWidgets.QMainWindow()
    ui = Ui_streetFighter()
    ui.setupUi(streetFighter)
    streetFighter.show()
    sys.exit(app.exec())
